name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # Tell the action to look inside your specific folder
      - run: flutter pub get
        working-directory: diet_management_app
        
      - run: flutter build web --release --base-href "/diet-tracker-dart-with-flutter/"
        working-directory: diet_management_app

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Make sure it picks up the build from the subfolder
          publish_dir: ./diet_management_app/build/web
